### ISSUE TITLE
The above error occurred while the Web server was processing your request

### ISSUE THREAD

**Issue by baur** [Streletz/tasktracker#2]
Server: Windows Server 2016
PHP 7.4
Apache 2.4

Дальше логина не работает
![image](https://user-images.githubusercontent.com/2898361/74824950-425c3c80-5333-11ea-99c3-fb71f77c9801.png)

```
<VirtualHost *:81>
    DocumentRoot "d:/WEB/xampp/htdocs/tasktracker/web"
    ServerName localhost.tasktracker.com  
    <Directory "d:/WEB/xampp/htdocs/tasktracker">
      Options Indexes MultiViews FollowSymLinks
      AllowOverride All
      Require all granted
    </Directory>
</VirtualHost>
```

теперь даже не могу открыть DASHBOARD XAMPP

![image](https://user-images.githubusercontent.com/2898361/74825269-d6c69f00-5333-11ea-8977-75c40752b696.png)

**Comment by baur** [comment]
```
2020-02-19 11:28:38 [::1][1][pqoeh9l8uiv431kjmk2s2mh2at][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined variable: params in D:\WEB\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php:111
Stack trace:
#0 D:\WEB\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php(111): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', 'D:\\WEB\\xampp\\ht...', 111, Array)
#1 D:\WEB\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php(62): app\modules\tasks\models\SearchTasks->prepareDataProvider(Object(yii\db\ActiveQuery))
#2 D:\WEB\xampp\htdocs\tasktracker\components\myTasks\myTasks.php(18): app\modules\tasks\models\SearchTasks->searchMyTasks(Array)
#3 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Widget.php(140): app\components\myTasks\MyTasks->run()
#4 D:\WEB\xampp\htdocs\tasktracker\views\site\index.php(8): yii\base\Widget::widget()
#5 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(336): require('D:\\WEB\\xampp\\ht...')
#6 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(254): yii\base\View->renderPhpFile('D:\\WEB\\xampp\\ht...', Array)
#7 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('D:\\WEB\\xampp\\ht...', Array, Object(app\controllers\SiteController))
#8 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Controller.php(384): yii\base\View->render('index', Array, Object(app\controllers\SiteController))
#9 D:\WEB\xampp\htdocs\tasktracker\controllers\SiteController.php(70): yii\base\Controller->render('index', Array)
#10 [internal function]: app\controllers\SiteController->actionIndex()
#11 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#12 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('index', Array)
#14 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('site/index', Array)
#15 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 D:\WEB\xampp\htdocs\tasktracker\web\index.php(14): yii\base\Application->run()
#17 {main}
2020-02-19 11:28:38 [::1][1][pqoeh9l8uiv431kjmk2s2mh2at][info][application] $_GET = []
```

**Comment by baur** [comment]
```
$_SERVER = [
    'REDIRECT_MIBDIRS' => 'D:/WEB/xampp/php/extras/mibs'
    'REDIRECT_MYSQL_HOME' => '\\xampp\\mysql\\bin'
    'REDIRECT_OPENSSL_CONF' => 'D:/WEB/xampp/apache/bin/openssl.cnf'
    'REDIRECT_PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php'
    'REDIRECT_PHPRC' => '\\xampp\\php'
    'REDIRECT_TMP' => '\\xampp\\tmp'
    'REDIRECT_STATUS' => '200'
    'MIBDIRS' => 'D:/WEB/xampp/php/extras/mibs'
    'MYSQL_HOME' => '\\xampp\\mysql\\bin'
    'OPENSSL_CONF' => 'D:/WEB/xampp/apache/bin/openssl.cnf'
    'PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php'
    'PHPRC' => '\\xampp\\php'
    'TMP' => '\\xampp\\tmp'
    'HTTP_HOST' => 'localhost:81'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'
    'HTTP_SEC_FETCH_USER' => '?1'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'HTTP_SEC_FETCH_SITE' => 'same-origin'
    'HTTP_SEC_FETCH_MODE' => 'navigate'
    'HTTP_REFERER' => 'http://localhost:81/admin/users/index'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9,ru;q=0.8'
    'HTTP_COOKIE' => 'PHPSESSID=pqoeh9l8uiv431kjmk2s2mh2at; _identity=9bad9fb0666e88e5ea5608113b12984f9143835c5d06034f7014e717f7f56b3da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A14%3A%22%5B1%2C%22%22%2C2592000%5D%22%3B%7D; _csrf=2df9f6ea6ac956972b6619a1ec24a9c0c6b807e128c2fbadb1b1b4fb8c03f6c0a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22u3VmyVoqOMruSYPW7pJ71jxko1--EWaF%22%3B%7D'
    'PATH' => 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps'
    'SystemRoot' => 'C:\\Windows'
    'COMSPEC' => 'C:\\Windows\\system32\\cmd.exe'
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
    'WINDIR' => 'C:\\Windows'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.41 (Win64) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1c PHP/7.4.2 Server at localhost Port 81</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.41 (Win64) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1c PHP/7.4.2'
    'SERVER_NAME' => 'localhost'
    'SERVER_ADDR' => '::1'
    'SERVER_PORT' => '81'
    'REMOTE_ADDR' => '::1'
    'DOCUMENT_ROOT' => 'D:/WEB/xampp/htdocs/tasktracker/web'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => 'D:/WEB/xampp/htdocs/tasktracker/web'
    'SERVER_ADMIN' => 'postmaster@localhost'
    'SCRIPT_FILENAME' => 'D:/WEB/xampp/htdocs/tasktracker/web/index.php'
    'REMOTE_PORT' => '50360'
    'REDIRECT_URL' => '/site/index'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/site/index'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1582108118.874
    'REQUEST_TIME' => 1582108118
]

```

**Comment by Streletz** [comment]
Как воспроизвести возникшую проблему? После чего это началось?

**Comment by baur** [comment]
- Установка в Windows Server 2016
- Настройка <VirtualHost *:81> (без этого даже не запускается напрямую tasktracker\web\index.php)
- успешный логин
- error

**Comment by Streletz** [comment]
> Настройка <VirtualHost *:81> (без этого даже не запускается напрямую tasktracker\web\index.php)

По умолчанию протокол HTTP использует 80 порт. Если помимо XAMPP в системе есть другие HTTP сервера, которые слушают этот порт (тот же IIS), то естественно возникает конфликт.  

Также вполне возможно, что порт просто закрыт (стандартный файрвол Windows настроен по умолчанию так, что 80 порт может использовать только HTTP клиент (тот же браузер)).

В любом случае, решение этого вопроса целиком в компетенции местной IT службы.

> - успешный логин
> - error

С этим уже сложнее.

Буквально сегодня я скачал последний стабильный релиз и развернул его с нуля под Win 10. Работает нормально.

Попробуйте использовать его.

**Comment by baur** [comment]
У меня порт 80 уже занято iis, поэтому Apache настроен на 81 порт

**Comment by Streletz** [comment]
> уже занято iis

Что и требовалось доказать. Но, повторюсь, это вопрос местной IT инфраструктуры и к софту никак не относится..

**Comment by baur** [comment]
Спасибо, если в принципе на Win10 запускается, дальше попробую разобраться!

**Comment by baur** [comment]
Все таки не работает, попробуйте портировать на MSSQL Server , возможно ошибка воспроизводиться ...

**Comment by Streletz** [comment]
К сожалению, пока приложение рассчитано только на MySQL и тестировалось на этой СУБД. В версии 4.0.0 будет добавлена поддержка PostgreSQL.

Возможность поддержки MS SQL Server изучается и возможно будет добавлена в одном из следующих релизов. На данном этапе адаптировать к MS SQL возможности нет.

**Comment by baur** [comment]
ясно, а я поднял на mssql и страдаю на ровном месте. Просто хотел интегрировать в другие системы, отчёты и т. д.
