### ISSUE TITLE
Undefined variable: params

### ISSUE THREAD

**Issue by baur** [Streletz/tasktracker#3]
OS: Windws Server 2016
DB: MySQL
Миграция успешно
для чистоты эксперимента запустил через: **php yii serve --port=8888**

Ошибка после успешного логина: 

```
2020-04-14 10:40:18 [::1][1][nennqoo5663ujus1ldq881930l][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined variable: params in E:\app\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php:111
Stack trace:
#0 E:\app\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php(111): yii\base\ErrorHandler->handleError()
#1 E:\app\xampp\htdocs\tasktracker\modules\tasks\models\SearchTasks.php(50): app\modules\tasks\models\SearchTasks->prepareDataProvider()
#2 E:\app\xampp\htdocs\tasktracker\modules\tasks\controllers\TasksController.php(91): app\modules\tasks\models\SearchTasks->search()
#3 [internal function]: app\modules\tasks\controllers\TasksController->actionIndex()
#4 E:\app\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()
#5 E:\app\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams()
#6 E:\app\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction()
#7 E:\app\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction()
#8 E:\app\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest()
#9 E:\app\xampp\htdocs\tasktracker\web\index.php(14): yii\base\Application->run()
#10 {main}
2020-04-14 10:40:18 [::1][1][nennqoo5663ujus1ldq881930l][info][application] $_GET = []

$_POST = []

$_FILES = []

$_COOKIE = [
    '__utma' => '111872281.987369622.1554093899.1554093899.1554093899.1'
    'metabase_SESSION' => '8363cef7-f4c2-4c81-9b88-7abaa4329e8d'
    'PHPSESSID' => 'nennqoo5663ujus1ldq881930l'
    '_identity' => '9bad9fb0666e88e5ea5608113b12984f9143835c5d06034f7014e717f7f56b3da:2:{i:0;s:9:\"_identity\";i:1;s:14:\"[1,\"\",2592000]\";}'
    '_csrf' => '3529048ac87a86c354e275fd172f1421900f988edd62649b3c4049e3c7bf185fa:2:{i:0;s:5:\"_csrf\";i:1;s:32:\"TVxBF3nivSfI3_iuGvm20qU0GOV2tlKF\";}'
]

$_SESSION = [
    '__flash' => []
    '__id' => 1
]

$_SERVER = [
    'DOCUMENT_ROOT' => 'E:\\app\\xampp\\htdocs\\tasktracker\\web'
    'REMOTE_ADDR' => '::1'
    'REMOTE_PORT' => '53842'
    'SERVER_SOFTWARE' => 'PHP 7.4.1 Development Server'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'SERVER_NAME' => 'localhost'
    'SERVER_PORT' => '8888'
    'REQUEST_URI' => '/tasks/tasks/index'
    'REQUEST_METHOD' => 'GET'
    'SCRIPT_NAME' => '/index.php'
    'SCRIPT_FILENAME' => 'E:\\app\\xampp\\htdocs\\tasktracker\\web\\index.php'
    'PATH_INFO' => '/tasks/tasks/index'
    'PHP_SELF' => '/index.php/tasks/tasks/index'
    'HTTP_HOST' => 'localhost:8888'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'
    'HTTP_SEC_FETCH_DEST' => 'document'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    'HTTP_SEC_FETCH_SITE' => 'same-origin'
    'HTTP_SEC_FETCH_MODE' => 'navigate'
    'HTTP_SEC_FETCH_USER' => '?1'
    'HTTP_REFERER' => 'http://localhost:8888/admin/users/index'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,kk;q=0.6,lb;q=0.5,bg;q=0.4,pt;q=0.3,cy;q=0.2'
    'HTTP_COOKIE' => '__utma=111872281.987369622.1554093899.1554093899.1554093899.1; metabase.SESSION=8363cef7-f4c2-4c81-9b88-7abaa4329e8d; PHPSESSID=nennqoo5663ujus1ldq881930l; _identity=9bad9fb0666e88e5ea5608113b12984f9143835c5d06034f7014e717f7f56b3da%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A14%3A%22%5B1%2C%22%22%2C2592000%5D%22%3B%7D; _csrf=3529048ac87a86c354e275fd172f1421900f988edd62649b3c4049e3c7bf185fa%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22TVxBF3nivSfI3_iuGvm20qU0GOV2tlKF%22%3B%7D'
    'REQUEST_TIME_FLOAT' => 1586839218.5288
    'REQUEST_TIME' => 1586839218
] 
```

**Comment by baur** [comment]
Версия PHP 7.4.1 Development Server как то влияет?

**Comment by Streletz** [comment]
В том то и дело, что данную ошибку на MySQL воспроизвести никак не удаётся. Иначе она уже давно была бы исправлена.

За обратную связь и подробную информацию спасибо! На её основе создал задачу в backlog версии 4.0.0. Когда дойдёт до её разработки попробую протестировать дополнительно. Но, ничего не обещаю.
