### ISSUE TITLE
Only variables should be passed by reference in

### ISSUE THREAD

**Issue by baur** [Streletz/tasktracker#6]
OS: Windows Server 2016
DB: Posgres v12
PHP: 7.4.16
PDO: PostgreSQL(libpq) Version | 11.4

http://127.0.10.80:81/admin/users/index

![image](https://user-images.githubusercontent.com/2898361/111451569-c3a32000-873b-11eb-9654-a874b46347a9.png)

```
yii\base\ErrorException: Only variables should be passed by reference in D:\WEB\xampp\htdocs\tasktracker\modules\admin\views\users\index.php:38
Stack trace:
#0 D:\WEB\xampp\htdocs\tasktracker\modules\admin\views\users\index.php(38): yii\base\ErrorHandler->handleError(8, 'Only variables ...', 'D:\\WEB\\xampp\\ht...', 38, Array)
#1 [internal function]: yii\base\View->{closure}(Object(app\modules\admin\models\Users), 1, 0, Object(yii\grid\DataColumn))
#2 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\DataColumn.php(230): call_user_func(Object(Closure), Object(app\modules\admin\models\Users), 1, 0, Object(yii\grid\DataColumn))
#3 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\DataColumn.php(244): yii\grid\DataColumn->getDataCellValue(Object(app\modules\admin\models\Users), 1, 0)
#4 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\Column.php(111): yii\grid\DataColumn->renderDataCellContent(Object(app\modules\admin\models\Users), 1, 0)
#5 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\GridView.php(520): yii\grid\Column->renderDataCell(Object(app\modules\admin\models\Users), 1, 0)
#6 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\GridView.php(489): yii\grid\GridView->renderTableRow(Object(app\modules\admin\models\Users), 1, 0)
#7 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\GridView.php(353): yii\grid\GridView->renderTableBody()
#8 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\widgets\BaseListView.php(160): yii\grid\GridView->renderItems()
#9 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\GridView.php(321): yii\widgets\BaseListView->renderSection('{items}')
#10 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\widgets\BaseListView.php(135): yii\grid\GridView->renderSection('{items}')
#11 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#12 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\widgets\BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...')
#13 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\grid\GridView.php(296): yii\widgets\BaseListView->run()
#14 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Widget.php(140): yii\grid\GridView->run()
#15 D:\WEB\xampp\htdocs\tasktracker\modules\admin\views\users\index.php(32): yii\base\Widget::widget(Array)
#16 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(336): require('D:\\WEB\\xampp\\ht...')
#17 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(254): yii\base\View->renderPhpFile('D:\\WEB\\xampp\\ht...', Array)
#18 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('D:\\WEB\\xampp\\ht...', Array, Object(app\modules\admin\controllers\UsersController))
#19 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Controller.php(384): yii\base\View->render('index', Array, Object(app\modules\admin\controllers\UsersController))
#20 D:\WEB\xampp\htdocs\tasktracker\modules\admin\controllers\UsersController.php(64): yii\base\Controller->render('index', Array)
#21 [internal function]: app\modules\admin\controllers\UsersController->actionIndex()
#22 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#23 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('index', Array)
#25 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/users/ind...', Array)
#26 D:\WEB\xampp\htdocs\tasktracker\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#27 D:\WEB\xampp\htdocs\tasktracker\web\index.php(16): yii\base\Application->run()
#28 {main}
```

**Comment by Streletz** [comment]
На проверке.

**Comment by Streletz** [comment]
Исправлено.

Исправление будет доступно в следующем предварительном релизе.
